name: Java CI with Maven

on:
  workflow_dispatch:
    inputs:
      profile:
        type: choice
        description: build with specific maven profile
        required: false
        options:
          - full
          - minimal-jars
          - minimal-reduced-jars
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        #        os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - if: "${{ github.event.inputs.profile == '' }}"
      name: Build with Maven
      run: mvn -B install
    - if: "${{ github.event.inputs.profile != '' }}"
      name: Build with Maven profile ${{ github.event.inputs.profile }}
      run: mvn -B install -P${{ github.event.inputs.profile }}

    - name: test (format a single .java file)
      # try to format a single .java file
      run: |
        echo "public class Test{    }" > Test.java
        java -jar idea-code-formatter/target/idea-code-formatter-*.jar -allowDefaults Test.java
        echo "d48d83fd8ed599c6da79ea93ace6f90f Test.java" > Test.java.formatted.md5
        if md5sum -c Test.java.formatted.md5;
          then TEST_EXITCODE=0
        else TEST_EXITCODE=1
        fi
        rm Test.java
        rm Test.java.formatted.md5
        exit $TEST_EXITCODE
